### ISSUE TITLE
To appear at ICASSP?

### ISSUE THREAD

**Issue by daisukelab** [ddlBoJack/MT4SSL#1]
Dear authors,
I'd like to cite your paper and let me check if it is to appear at ICASSP.
Thanks for your help!

**Comment by ddlBoJack** [comment]
Thank you for your recognition of our work. Unfortunately, the paper was rejected despite all of the reviewers agreeing to accept it. You can cite the version we uploaded on arxiv.

**Comment by daisukelab** [comment]
Thanks for your quick answer.
I'm very surprised... and shocked because your paper looks great.
Honestly, I am terrified by the review process that happened to you.
Please be sure to submit it to Interspeech.
I like your idea and I think yours have a good novelty that combines data2vec and HuBERT with solid results.
Good luck with your next try.
I will cite your arXiv version, though the Interspeech guideline seems to accept only the published papers in reference.

**Comment by ddlBoJack** [comment]
Here is the guidance for INTERSPEECH2023:
> References to non-peer-reviewed publications (including public repositories such as arXiv, Preprints, and HAL, software, and personal communications) **should only be made if there is no peer-reviewed publication available**.

So take it easy to cite us!

**Comment by daisukelab** [comment]
Aha! thank you for letting me know about that! :)

**Comment by daisukelab** [comment]
@ddlBoJack
Hi, this is our paper to appear at Interspeech2023, citing yours:
https://arxiv.org/abs/2305.14079
Thanks for your insightful research!

**Comment by ddlBoJack** [comment]
> 

MT4SSL will also appear at Interspeech2023. Thanks for your appreciation!

**Comment by daisukelab** [comment]
See ya in Dublin! ;)
