### ISSUE TITLE
What does this pre-trained model do for the front-end?

### ISSUE THREAD

**Issue by JusperLee** [ddlBoJack/MT4SSL#2]
This work is very inspiring.
I'm not sure if it's possible to think of an encoder that can be used on the front end like Hubert? Or for Speechtokenizer's loss alignment.
Do you have any thoughts or insights?

**Comment by ddlBoJack** [comment]
Hi Kai, I did not get your core idea. Maybe we can chat on WeChat.

**Comment by JusperLee** [comment]
Ok. My WeChat num: ThuKaiLi.
